services:
  # Servicio de MongoDB
  mongodb:
    image: mongo:latest
    container_name: whatsapp-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - whatsapp-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Servicio de WhatsApp Bot
  whatsapp-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-bot
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - whatsapp_session:/app/session
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/whatsapp_bot
      - SESSION_DATA_PATH=/app/session
    networks:
      - whatsapp-network

volumes:
  mongodb_data:
  whatsapp_session:
  node_modules:

networks:
  whatsapp-network:
    driver: bridge
